version: '3'
services:
  game-upload-dev:
    image: "game-upload-dev"
    build: .
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      # ファイル変化でリロードするために、プロジェクトの全ファイルをマウント
      - .:/app
      # node_modulesを除外するため、適当な名前(ignore)のvolumeをマウント
      - ignore:/app/node_modules
    env_file:
      - node.env
      - docker-dev.env
    networks: 
      - network-mongo

volumes:
  ignore:

networks: 
  network-mongo:
    external: true
