version: '3'
services:
  game-upload-test:
    image: "game-upload-test"
    build: .
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
    depends_on:
      - "mongo"
    env_file:
      - node.env
      - docker-test.env

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - db-volume_test:/data/db
      - db-config-volume_test:/data/configdb

volumes:
  db-volume_test:
  db-config-volume_test:
