version: '3'
services:
  appnavi-works:
    build: .
    container_name: appnavi-works_development
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      - ./private:/app/private
      - ./public:/app/public
      - ./src:/app/src
      - ./views:/app/views
      - ./migrate-mongo:/app/migrate-mongo
    environment: 
      - NODE_ENV=development
      - SITE_URL=${SITE_URL_DEVELOPMENT}
      - WORK_STORAGE_SIZE_BYTES=53687091200 # 50 * 1024^3 bytes = 50GB
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - db
    secrets:
      - DATABASE_URL
      - SESSION_DATABASE_URL
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_WORKSPACE_ID
      - COOKIE_NAME
      - COOKIE_KEYS
      - JWT_SECRET
      - COOKIE_SECRET
  mongo:
    image: "mongo:5.0.12"
    expose:
      - "27017"
    volumes:
      - db-volume-appnavi-works:/data/db
      - db-config-volume-appnavi-works:/data/configdb
    networks:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
volumes:
  db-volume-appnavi-works:
  db-config-volume-appnavi-works:
networks:
  db:
    driver: bridge
secrets:
  DATABASE_URL:
    file: ./secrets/development/database_url.txt
  SESSION_DATABASE_URL:
    file: ./secrets/development/session_database_url.txt
  SLACK_CLIENT_ID:
    file: ./secrets/development/slack_client_id.txt
  SLACK_CLIENT_SECRET:
    file: ./secrets/development/slack_client_secret.txt
  SLACK_WORKSPACE_ID:
    file: ./secrets/development/slack_workspace_id.txt
  COOKIE_NAME:
    file: ./secrets/development/cookie_name.txt
  COOKIE_KEYS:
    file: ./secrets/development/cookie_keys.txt
  JWT_SECRET:
    file: ./secrets/development/jwt_secret.txt
  COOKIE_SECRET:
    file: ./secrets/development/cookie_secret.txt
  MONGO_ROOT_USERNAME:
    file: ./secrets/development/mongo_root_username.txt
  MONGO_ROOT_PASSWORD:
    file: ./secrets/development/mongo_root_password.txt
