version: '3'
services:
  game-upload-test:
    image: "game-upload-test"
    build: .
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
    env_file:
      - node.env
      - docker-test.env
    networks: 
      - network-mongo

networks: 
  network-mongo:
    external: true
