version: '3'
services:
  appnavi-works:
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
      - ./src:/app/src
    env_file:
      - .env
    environment: 
      - NODE_ENV=test
      - SITE_URL=http://localhost:3000
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
