version: '3'
services:
  appnavi-works:
    build: .
    environment:
      - WORK_STORAGE_SIZE_BYTES=53687091200 # 50 * 1024^3 bytes = 50GB
      - PORT=3000
      - NODE_ENV=test
      - SITE_URL=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - db
    secrets:
      - DATABASE_URL
      - SESSION_DATABASE_URL
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_WORKSPACE_ID
      - COOKIE_NAME
      - COOKIE_KEYS
      - JWT_SECRET
      - COOKIE_SECRET
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
      - ./src:/app/src
  mongo:
    image: "mongo:5.0.6"
    expose:
      - "27017"
    volumes:
      - db-volume-appnavi-works:/data/db
      - db-config-volume-appnavi-works:/data/configdb
    networks:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD

volumes:
  db-volume-appnavi-works:
  db-config-volume-appnavi-works:

networks:
  db:
    driver: bridge


secrets:
  DATABASE_URL:
    file: ./secrets/test/database_url.txt    
  SESSION_DATABASE_URL:
    file: ./secrets/test/session_database_url.txt
  SLACK_CLIENT_ID:
    file: ./secrets/test/slack_client_id.txt
  SLACK_CLIENT_SECRET:
    file: ./secrets/test/slack_client_secret.txt
  SLACK_WORKSPACE_ID:
    file: ./secrets/test/slack_workspace_id.txt
  COOKIE_NAME:
    file: ./secrets/test/cookie_name.txt
  COOKIE_KEYS:
    file: ./secrets/test/cookie_keys.txt
  JWT_SECRET:
    file: ./secrets/test/jwt_secret.txt
  COOKIE_SECRET:
    file: ./secrets/test/cookie_secret.txt
  MONGO_ROOT_USERNAME:
    file: ./secrets/test/mongo_root_username.txt
  MONGO_ROOT_PASSWORD:
    file: ./secrets/test/mongo_root_password.txt
