version: '3'
services:
  appnavi-works:
    restart: always
    command: "yarn run start"
    volumes: 
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - SITE_URL=https://resources.opuappnavi.com
      - SLACK_REDIRECT_URI="https://resources.opuappnavi.com/auth/redirect
      - "VIRTUAL_HOST=resources.opuappnavi.com"
      - "LETSENCRYPT_HOST=resources.opuappnavi.com"
    networks:
      - nginx-proxy
  mongo:
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD

networks: 
  nginx-proxy:
    external: 
      name: nginx-proxy
