version: '3'
services:
  game-upload:
    command: "yarn run dev"
    volumes: 
      - ./private:/app/private
      - ./public:/app/public
      - ./src:/app/src
      - ./src_browser:/app/src_browser
      - ./views:/app/views
    env_file:
      - docker-dev.env
