version: '3'
services:
  appnavi-works:
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
      - ./src:/app/src
    env_file:
      - docker-test.env
      - .env
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
