version: '3'
services:
  appnavi-works:
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      - ./private:/app/private
      - ./public:/app/public
      - ./src:/app/src
      - ./views:/app/views
    env_file:
      - docker-dev.env
