version: '3'
services:
  game-upload:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - node.env
  mongo:
    image: "mongo"
    expose: 
      - "27017"
    volumes:
      - db-volume-game-upload:/data/db
      - db-config-volume-game-upload:/data/configdb
        
volumes:
  db-volume-game-upload:
  db-config-volume-game-upload:
