version: '3'
services:
  appnavi-works:
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
      - ./src:/app/src
    environment: 
      - NODE_ENV=test
      - SITE_URL=http://localhost:3000
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD