version: '3'
services:
  appnavi-works:
    restart: always
    command: "yarn run start"
    volumes: 
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
    env_file:
      - docker-production.env
    environment:
      - "VIRTUAL_HOST=resources.opuappnavi.com"
      - "LETSENCRYPT_HOST=resources.opuappnavi.com"
    networks:
      - nginx-proxy
  mongo:
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD

networks: 
  nginx-proxy:
    external: 
      name: nginx-proxy
