version: '3'
services:
  appnavi-works:
    build:
      dockerfile: docker/development.Dockerfile
      context: .
    environment:
      - WORK_STORAGE_SIZE_BYTES=53687091200 # 50 * 1024^3 bytes = 50GB
      - PORT=3000
      - NODE_ENV=test
      - SITE_URL=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - db
    secrets:
      - DATABASE_URL
      - SESSION_DATABASE_URL
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_WORKSPACE_ID
      - COOKIE_SECRET
      - CSRF_TOKEN_SECRET
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
    command: "yarn workspace server run test"
    volumes:
      - ./server/test:/app/server/test
      - ./server/src:/app/server/src
  mongo:
    image: "mongo:6.0.2"
    expose:
      - "27017"
    networks:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD

networks:
  db:
    driver: bridge

secrets:
  DATABASE_URL:
    file: ./secrets/test/database_url.txt
  SESSION_DATABASE_URL:
    file: ./secrets/test/session_database_url.txt
  SLACK_CLIENT_ID:
    file: ./secrets/test/slack_client_id.txt
  SLACK_CLIENT_SECRET:
    file: ./secrets/test/slack_client_secret.txt
  SLACK_WORKSPACE_ID:
    file: ./secrets/test/slack_workspace_id.txt
  COOKIE_SECRET:
    file: ./secrets/test/cookie_secret.txt
  CSRF_TOKEN_SECRET:
    file: ./secrets/test/csrf_token_secret.txt
  MONGO_ROOT_USERNAME:
    file: ./secrets/test/mongo_root_username.txt
  MONGO_ROOT_PASSWORD:
    file: ./secrets/test/mongo_root_password.txt
