version: '3'
services:
  game-upload:
    image: "game-upload"
    build: .
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      # ファイル変化でリロードするために、プロジェクトの全ファイルをマウント
      - .:/app
      # node_modulesを除外するため、適当な名前(ignore)のvolumeをマウント
      - ignore:/app/node_modules
    depends_on:
      - "mongo"
    env_file:
      - node.env
    environment: 
      - NODE_ENV=development
      - SLACK_REDIRECT_URI=http://localhost:3000/auth/redirect
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
      - db-config-volume:/data/configdb

volumes:
  db-volume:
  db-config-volume:
  ignore:
