version: '3'
services:
  game-upload:
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      - ./private:/app/private
      - ./public:/app/public
      - ./src:/app/src
      - ./views:/app/views
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    env_file:
      - docker-dev.env
