version: '3'
services:
  game-upload:
    command: "yarn run test"
    ports:
      - "3000:3000"
    volumes: 
      - ./test:/app/test
      - ./src:/app/src
    env_file:
      - docker-test.env

