version: '3'
services:
  appnavi-works:
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      - ./private:/app/private
      - ./public:/app/public
      - ./src:/app/src
      - ./views:/app/views
      - ./migrate-mongo:/app/migrate-mongo
    environment: 
      - NODE_ENV=development
      - SITE_URL=${APPNAVI_WORKS_DEV_URI}

  mongo:
    container_name: appnavi-works_mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
