version: "3"
services:
  appnavi-works:
    build:
      dockerfile: docker/production.Dockerfile
      context: .
    container_name: appnavi-works_production
    restart: always
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
    environment:
      - WORK_STORAGE_SIZE_BYTES=53687091200 # 50 * 1024^3 bytes = 50GB
      - PORT=3000
      - NODE_ENV=production
      - SITE_URL=https://resources.opuappnavi.com
    depends_on:
      - mongo
    networks:
      - db
      - https-portal
    secrets:
      - DATABASE_URL
      - SESSION_DATABASE_URL
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_WORKSPACE_ID
      - COOKIE_SECRET
      - CSRF_TOKEN_SECRET
  mongo:
    image: "mongo:6.0.2"
    restart: always
    expose:
      - "27017"
    volumes:
      - db-volume-appnavi-works:/data/db
      - db-config-volume-appnavi-works:/data/configdb
    networks:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
    secrets:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
volumes:
  db-volume-appnavi-works:
  db-config-volume-appnavi-works:


networks:
  db:
    driver: bridge
  https-portal:
    name: https-portal
    external: true

secrets:
  DATABASE_URL:
    file: ./secrets/production/database_url.txt
  SESSION_DATABASE_URL:
    file: ./secrets/production/session_database_url.txt
  SLACK_CLIENT_ID:
    file: ./secrets/production/slack_client_id.txt
  SLACK_CLIENT_SECRET:
    file: ./secrets/production/slack_client_secret.txt
  SLACK_WORKSPACE_ID:
    file: ./secrets/production/slack_workspace_id.txt
  COOKIE_SECRET:
    file: ./secrets/production/cookie_secret.txt
  CSRF_TOKEN_SECRET:
    file: ./secrets/production/csrf_token_secret.txt
  MONGO_ROOT_USERNAME:
    file: ./secrets/production/mongo_root_username.txt
  MONGO_ROOT_PASSWORD:
    file: ./secrets/production/mongo_root_password.txt
