version: '3'
services:
  game-upload:
    build: .
    env_file:
      - node.env
    depends_on:
      - mongo
    networks:
      - db
  mongo:
    image: "mongo"
    expose: 
      - "27017"
    volumes:
      - db-volume-game-upload:/data/db
      - db-config-volume-game-upload:/data/configdb
    networks:
      - db

volumes:
  db-volume-game-upload:
  db-config-volume-game-upload:

networks:
  db:
    driver: bridge