version: '3'
services:
  game-upload:
    build: .
    command: "yarn run start"
    ports:
      - "3000:3000"
    volumes: 
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
    env_file:
      - node.env
      - docker-production.env
    networks: 
      - network-mongo

networks: 
  network-mongo:
    external: true
