version: '3'
services:
  appnavi-works:
    container_name: appnavi-works
    restart: always
    command: "yarn run start"
    volumes: 
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - SITE_URL=https://resources.opuappnavi.com
    networks:
      - https-portal
  mongo:
    restart: always

networks: 
  https-portal:
    external: 
      name: https-portal
