version: '3'
services:
  appnavi-works:
    build: .
    env_file:
      - node.env
    depends_on:
      - mongo
    networks:
      - db
  mongo:
    image: "mongo"
    expose: 
      - "27017"
    volumes:
      - db-volume-appnavi-works:/data/db
      - db-config-volume-appnavi-works:/data/configdb
    networks:
      - db

volumes:
  db-volume-appnavi-works:
  db-config-volume-appnavi-works:

networks:
  db:
    driver: bridge