version: '3'
services:
  game-upload-test:
    image: "game-upload-test"
    build: .
    command: "yarn run test"
    volumes: 
      - ./test:/app/test
    depends_on:
      - "mongo"
    env_file:
      - node.env
    environment: 
      - NODE_ENV=development
      - SLACK_REDIRECT_URI=http://localhost:3000/auth/redirect
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
      - db-config-volume:/data/configdb

volumes:
  db-volume:
  db-config-volume:
