version: '3'
services:
  game-upload:
    image: "game-upload"
    build: .
    command: "yarn run start"
    ports:
      - "3000:3000"
    volumes: 
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
    depends_on:
      - "mongo"
    env_file:
      - node.env
    environment: 
      - NODE_ENV=production
      # TODO：本番のURLに変更
      - SLACK_REDIRECT_URI=http://localhost:3000/auth/redirect
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
      - db-config-volume:/data/configdb

volumes:
  db-volume:
  db-config-volume:
