version: '3'
services:
  game-upload-dev:
    image: "game-upload-dev"
    build: .
    command: "yarn run dev"
    ports:
      - "3000:3000"
    volumes: 
      # ファイル変化でリロードするために、プロジェクトの全ファイルをマウント
      - .:/app
      # node_modulesを除外するため、適当な名前(ignore)のvolumeをマウント
      - ignore:/app/node_modules
    depends_on:
      - "mongo"
    env_file:
      - node.env
      - docker-dev.env
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - db-volume_dev:/data/db
      - db-config-volume_dev:/data/configdb

volumes:
  db-volume_dev:
  db-config-volume_dev:
  ignore:
