#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

scriptName=`basename $0`
gitHookPath=`pwd`"/.git/hooks/$scriptName"
if [ -e $gitHookPath ];
then
  . $gitHookPath
fi

# 次のURLを参考に修正：https://github.com/yarnpkg/yarn/issues/2998#issuecomment-351424672
yarn --non-interactive lint </dev/tty